### ISSUE TITLE
Memcache on Acquia Pipelines?

### ISSUE THREAD

**Issue by justinlevi** [acquia/pipelines-examples#31]
With Travis, you can define additional php extensions that need to be included.

https://github.com/acquia/pipelines-examples/blob/20ba38ec3400ef8e5df0c0a91f924c52903f5c7f/tutorial-801/vendor/doctrine/cache/tests/travis/php.ini

```
services:
- memcached
```

```
- echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini || echo "Added memcached php extension";
```
source: https://github.com/acquia/blt/pull/3080/files

How would we do this on Acquia pipelines?

Seeing this issue in my pipelines logs and not sure how to proceed
```
Drupal\Core\Installer\Exception\InstallerException: Memcache:            [error]
Extensions not available
```

**Comment by vamche** [comment]
Pipelines YAML version 1.3.0 supports memcached as a service, for more details please refer: https://docs.acquia.com/acquia-cloud/develop/pipelines/yaml/#services-memcached
